### ISSUE TITLE
Progrmación de Contacto

### ISSUE THREAD

**Issue by mgl23** [onixmedia/Proeza#10]

**Comment by mgl23** [comment]
Falta el estilo y ya le pedi al cliente el correo que les va llegar la forma

**Comment by mgl23** [comment]
El correo que debe de llegar es al: proeza.corporativo@proeza.com.mx

**Comment by femedrano** [comment]
Link: http://proeza.com.mx.c25.sitepreviewer.com/wp-demo/contacto/
