### ISSUE TITLE
Programación Bolsa de Trabajo.

### ISSUE THREAD

**Issue by mgl23** [onixmedia/Proeza#13]

**Comment by femedrano** [comment]
Ya la terminé. Aquí está el link:

http://proeza.com.mx.c25.sitepreviewer.com/wp-demo/oportunidad-de-empleo/

**Comment by mgl23** [comment]
Estan muy bien los estilos, gracias Frida, 

Vi dos detalles que faltarían en la 
- [ ]  Ajuste en tablet de iconos centrados
  <img width="620" alt="captura de pantalla 2016-02-09 a la s 12 56 28" src="https://cloud.githubusercontent.com/assets/9618389/12927618/ab064cf4-cf2e-11e5-8e47-a8bea8bafe3c.png">
- [ ] Funcionalidad de ver más con texto escondido 
  <img width="360" alt="captura de pantalla 2016-02-09 a la s 12 54 59" src="https://cloud.githubusercontent.com/assets/9618389/12927620/af3c03ea-cf2e-11e5-8454-a7756bb6286b.png">

**Comment by femedrano** [comment]
Link: http://proeza.com.mx.c25.sitepreviewer.com/wp-demo/oportunidad-de-empleo/

Cambie: Orden de información de programa Delta, peso de la info de programa delta (de Gotham Light a Gotham Book), botón de enviar correo a rojo (los de ver más en azul, los demás en rojo)

**Comment by femedrano** [comment]
Botón del bloque únete al equipo, nose a dónde dirigirlo, porque ya se está en la página de oportunidades de empleo.

**Comment by femedrano** [comment]
Link: http://proeza.com.mx.c25.sitepreviewer.com/wp-demo/oportunidad-de-empleo/

**Comment by mgl23** [comment]
<img width="246" alt="captura de pantalla 2016-02-24 a la s 11 25 55" src="https://cloud.githubusercontent.com/assets/9618389/13294427/7fd90690-dae9-11e5-8374-46224465de57.png">
Tiene un pequeño error una I antes en el botón

y la liga debe de ser un mail to: reclutamiento@proeza.com.mx

**Comment by femedrano** [comment]
Link: http://proeza.com.mx.c25.sitepreviewer.com/wp-demo/oportunidad-de-empleo/
