### ISSUE TITLE
Programación de Página Básica

### ISSUE THREAD

**Issue by mgl23** [onixmedia/Proeza#14]
Página Básica

**Comment by femedrano** [comment]
Link: http://proeza.com.mx.c25.sitepreviewer.com/wp-demo/pagina-plana/

**Comment by mgl23** [comment]
Gracias Frida esta muy bien, solo hay que ponerle estilo a los links de todo el sitio como que el theme agarra un celeste que no va. 

<img width="412" alt="captura de pantalla 2016-02-10 a la s 15 25 26" src="https://cloud.githubusercontent.com/assets/9618389/12962340/a495daf6-d00a-11e5-8e6b-1b32a356f8e4.png">

**Comment by femedrano** [comment]
¿Me podrías decir cuales son los estilos de los links?
Supongo que si hay un link será amarillo, pero ¿cuando haya hover? o ¿cuando ya este visitado? ¿que colores van a querer?

**Comment by femedrano** [comment]
Link: http://proeza.com.mx.c25.sitepreviewer.com/wp-demo/pagina-plana/
