### ISSUE TITLE
Home: Bloque Oportunidad de empleo 

### ISSUE THREAD

**Issue by mgl23** [onixmedia/Proeza#29]
- [x] Estilar correctamente el título
- [x] Que la líga te lleve a la página correspondiente. 

<img width="662" alt="captura de pantalla 2016-02-05 a la s 12 26 16" src="https://cloud.githubusercontent.com/assets/9618389/12855225/d788b6d2-cc03-11e5-89ca-1d080e3b2224.png">

**Comment by femedrano** [comment]
Link: http://proeza.com.mx.c25.sitepreviewer.com/wp-demo/
