### ISSUE TITLE
[Programación]  Responsabilidad Social

### ISSUE THREAD

**Issue by mgl23** [onixmedia/Proeza#30]
Programación y front de la página Responsabilidad Social

**Comment by femedrano** [comment]
Link: http://proeza.com.mx.c25.sitepreviewer.com/wp-demo/responsabilidad-social/

**Comment by mgl23** [comment]
hay que cambiar la foto por una libre de derechos y que tenga universitarios, ya que la fundación es para estudiantes no para niños 
<img width="536" alt="captura de pantalla 2016-02-09 a la s 17 54 57" src="https://cloud.githubusercontent.com/assets/9618389/12952231/648be54c-cfdb-11e5-9b4b-6ae198d7ee7a.png">

La type de los valores no es gotham, quedo con georgia 
<img width="452" alt="captura de pantalla 2016-02-10 a la s 9 49 47" src="https://cloud.githubusercontent.com/assets/9618389/12952325/c3020be2-cfdb-11e5-8cbf-e69e9fd1c44d.png">

falta agregar funcionalidad ver más
<img width="147" alt="captura de pantalla 2016-02-09 a la s 17 53 56" src="https://cloud.githubusercontent.com/assets/9618389/12953176/eaa89b54-cfde-11e5-8715-29c7c0d3ec26.png">

**Comment by femedrano** [comment]
Link: http://proeza.com.mx.c25.sitepreviewer.com/wp-demo/responsabilidad-social/

**Comment by mgl23** [comment]
Gracias lo cierro y creo otro con los ajustes del cliente, que es algo aparte.
