### ISSUE TITLE
[Sección] Degradado en texto

### ISSUE THREAD

**Issue by mgl23** [onixmedia/Proeza#32]
<img width="279" alt="captura de pantalla 2016-02-11 a la s 16 28 55" src="https://cloud.githubusercontent.com/assets/9618389/12993121/ff281b54-d0dd-11e5-8a9e-2ca80816d73d.png">

Cambiar cada una de la páginas a su color correspondiente y que el código funcione en los exploradores  (firefox, safari, ie y chrome)

**Comment by jcabral02** [comment]
Ya resolví este problema, agregue con CSS el degradado con los colores definidos para cada sección y definimos un color base para la tipografía en caso de que el browser no sea compatible con esas propiedades.
