### ISSUE TITLE
[Citrofrut] Estilos de página

### ISSUE THREAD

**Issue by mgl23** [onixmedia/Proeza#33]
<img width="812" alt="captura de pantalla 2016-02-11 a la s 16 41 01" src="https://cloud.githubusercontent.com/assets/9618389/12993173/443c0958-d0de-11e5-97f3-da133b4cb7d6.png">

**Comment by femedrano** [comment]
http://proeza.com.mx.c25.sitepreviewer.com/wp-demo/citrofrut/

**Comment by mgl23** [comment]
Hay que cambiar la imagen de ir a blosa de trabajo, porque es de metalsa.

<img width="397" alt="captura de pantalla 2016-02-18 a la s 11 15 50" src="https://cloud.githubusercontent.com/assets/9618389/13151721/09a9cf70-d631-11e5-9435-5a5e2772d1d7.png">

Te anexo una imagen para que puedas poner 
![37866_105233256198185_1329576_n](https://cloud.githubusercontent.com/assets/9618389/13151735/1ee14148-d631-11e5-8a73-19ae417bdca3.jpg)

**Comment by jcabral02** [comment]
Listo Miguel, ya quedo resuelto, saludos!

**Comment by mgl23** [comment]
Gracias
