### ISSUE TITLE
[Zanitas] Estilos de página

### ISSUE THREAD

**Issue by mgl23** [onixmedia/Proeza#34]
<img width="789" alt="captura de pantalla 2016-02-11 a la s 16 42 26" src="https://cloud.githubusercontent.com/assets/9618389/12993213/73dda7d4-d0de-11e5-8331-25118a97f10d.png">

**Comment by femedrano** [comment]
http://proeza.com.mx.c25.sitepreviewer.com/wp-demo/zanitas/
