### ISSUE TITLE
[Astrum] Estilos de página

### ISSUE THREAD

**Issue by mgl23** [onixmedia/Proeza#35]
<img width="807" alt="captura de pantalla 2016-02-11 a la s 16 43 29" src="https://cloud.githubusercontent.com/assets/9618389/12993243/99a5dd24-d0de-11e5-87f4-e48b3a1cbcc5.png">

**Comment by femedrano** [comment]
http://proeza.com.mx.c25.sitepreviewer.com/wp-demo/astrum/
