### ISSUE TITLE
[Areya] Estilos de Página 

### ISSUE THREAD

**Issue by mgl23** [onixmedia/Proeza#36]
<img width="782" alt="captura de pantalla 2016-02-11 a la s 16 44 20" src="https://cloud.githubusercontent.com/assets/9618389/12993267/b60f5c06-d0de-11e5-9f87-df9f85174391.png">

**Comment by femedrano** [comment]
http://proeza.com.mx.c25.sitepreviewer.com/wp-demo/areya/

**Comment by mgl23** [comment]
Esta muy bien el estilo lo voy a cerrar y creo nuevos cuando estemos poblando el sitio, por ejemplo que no tiene página web y no debe de salir el botón :)
