### ISSUE TITLE
[General] Funcionalidad ver más

### ISSUE THREAD

**Issue by mgl23** [onixmedia/Proeza#37]
Funcionalidad accordion de ver más. 

<img width="172" alt="captura de pantalla 2016-02-11 a la s 16 47 25" src="https://cloud.githubusercontent.com/assets/9618389/12993325/255b65b4-d0df-11e5-9cfa-79531e544e1e.png">

La funcionalidad es que al dar clic se despliega texto ''escondido''

**Comment by jcabral02** [comment]
Se agrego al theme de Wp jQuery y con eso pudimos agregar la funcionalidad requerida para este efecto.
Ya quedo listo, se puede ver en la siguiente liga:
http://proeza.com.mx.c25.sitepreviewer.com/wp-demo/responsabilidad-social/

Saludos

**Comment by mgl23** [comment]
Gracias!
