### ISSUE TITLE
Plugin para Tradución

### ISSUE THREAD

**Issue by mgl23** [onixmedia/Proeza#4]

**Comment by jcabral02** [comment]
Se revisaron varias alternativas para hacer el sitio Multi lenguaje, todas basadas en el uso de plugins que se instalarían en el sitio. Las mejores opciones, en base a calificación de usuarios, popularidad, soporte y compatibilidad para el proyecto son: 

[Polylang](https://es.wordpress.org/plugins/polylang/)
Este es un plugin gratuito, muy usado y con una buena calificación por los usuarios que lo han implementado en sus proyectos. El problema es que al ser gratuito, las actualizaciones pueden ser menos periódicas y el soporte es con la comunidad.

[Wpml](https://wpml.org/) 
Este es un plugin profesional, con mucho soporte y actualizaciones, el problema es que tiene un costo de $30 dls y una renovación anual de $15 dls por año.

Para este proyecto decidimos implementar **Polylang**, con la posibilidad de cambiar mas adelante a Wpml, si así se decide por alguna dificultad técnica o de compatibilidad no detectada hasta este momento.

En este momento el plugin ya esta instalado. Y comenzaremos con su uso.
