### ISSUE TITLE
Programación: Presencia

### ISSUE THREAD

**Issue by femedrano** [onixmedia/Proeza#40]
Link: http://proeza.com.mx.c25.sitepreviewer.com/wp-demo/presencia/

**Comment by mgl23** [comment]
Ya sólo falta subir las imagenes en x2 para retina 
<img width="124" alt="captura de pantalla 2016-02-24 a la s 11 28 24" src="https://cloud.githubusercontent.com/assets/9618389/13294475/bd3667a8-dae9-11e5-9ead-c993296c29d1.png">

**Comment by femedrano** [comment]
Link: http://proeza.com.mx.c25.sitepreviewer.com/wp-demo/presencia/
