### ISSUE TITLE
[QA] Bloque presencia

### ISSUE THREAD

**Issue by mgl23** [onixmedia/Proeza#42]
<img width="551" alt="captura de pantalla 2016-02-26 a la s 12 53 19" src="https://cloud.githubusercontent.com/assets/9618389/13362076/f819c4d8-dc87-11e5-8182-208184ccef87.png">
Que tenga el mismo espacio arriba que abajo  ahorita arriba tiene 104px y abajo 84 px.

**Comment by femedrano** [comment]
link: http://proeza.com.mx.c25.sitepreviewer.com/

**Comment by mgl23** [comment]
Cambiar color de texto gris a #A98206
