### ISSUE TITLE
[QA] Bloque de Unidades de Negocio

### ISSUE THREAD

**Issue by mgl23** [onixmedia/Proeza#43]
<img width="1229" alt="captura de pantalla 2016-02-26 a la s 12 54 44" src="https://cloud.githubusercontent.com/assets/9618389/13362114/2ae8aa28-dc88-11e5-9028-9e0f73264ab8.png">

Falta: 
- [ ]  Que todas tengan el mismo, que no varie el espacio de las cajas blancas y que no este pegado la imagen con el texto. 
- [ ]  Que el logotipo este en tamaño correcto cada uno.
- [ ]  Que tenga liga a su página respectiva

**Comment by ramiross89** [comment]
Listo, móvil también
http://proeza.com.mx.c25.sitepreviewer.com/
