### ISSUE TITLE
Filosofía- Bloque Logos móvil y tablet

### ISSUE THREAD

**Issue by femedrano** [onixmedia/Proeza#55]
Movil
![screen shot 2016-03-04 at 10 25 46 am](https://cloud.githubusercontent.com/assets/16901017/13532899/8bc50916-e1f3-11e5-84d9-e56020336165.png)

Tablet 
![screen shot 2016-03-04 at 10 28 18 am](https://cloud.githubusercontent.com/assets/16901017/13532970/df105bb6-e1f3-11e5-81be-0211d067c047.png)

**Comment by ramiross89** [comment]
Listo
http://proeza.com.mx.c25.sitepreviewer.com/filosofia/

**Comment by mgl23** [comment]
Puede ser también si se dificulta una ilera de un logo abajo del otro.
