### ISSUE TITLE
[Móvil] Bloque presencia móvil

### ISSUE THREAD

**Issue by mgl23** [onixmedia/Proeza#62]
Estilar correctamente  <img width="400" alt="captura de pantalla 2016-03-04 a la s 16 57 17" src="https://cloud.githubusercontent.com/assets/9618389/13542705/37e9e92e-e22a-11e5-972e-c563a973ea35.png">

**Comment by femedrano** [comment]
link: http://proeza.com.mx.c25.sitepreviewer.com/
