### ISSUE TITLE
[Móvil QA] Imagen Zanitas 

### ISSUE THREAD

**Issue by mgl23** [onixmedia/Proeza#63]
La imagen zanitas no se ve. 
![img_3124](https://cloud.githubusercontent.com/assets/9618389/13543119/ed611220-e22d-11e5-90ea-fba5cfb580c3.PNG)

**Comment by femedrano** [comment]
![screen shot 2016-03-08 at 12 46 50 pm](https://cloud.githubusercontent.com/assets/16901017/13612215/e155ba52-e52b-11e5-87d3-67ab9c437dc6.png)

Link: http://proeza.com.mx.c25.sitepreviewer.com/zanitas/
