### ISSUE TITLE
[Móvil QA]  Responsabilidad Social

### ISSUE THREAD

**Issue by mgl23** [onixmedia/Proeza#64]
Responsabilidad Social hay que hacer más pequeña la font, ya que no se ve. 
![img_3125](https://cloud.githubusercontent.com/assets/9618389/13543130/fc2692f8-e22d-11e5-91b0-c9438a0661ed.PNG)

**Comment by femedrano** [comment]
![screen shot 2016-03-08 at 1 33 02 pm](https://cloud.githubusercontent.com/assets/16901017/13613581/5dae1d32-e532-11e5-9bc7-c7f27a415f01.png)
Para Todos los títulos 

Link de ejemplo: http://proeza.com.mx.c25.sitepreviewer.com/responsabilidad-social/
