### ISSUE TITLE
[Ingles] Doble Footer en Ingles

### ISSUE THREAD

**Issue by mgl23** [onixmedia/Proeza#67]
Se ve doble footer en ingles. 
<img width="1347" alt="captura de pantalla 2016-03-07 a la s 16 12 22" src="https://cloud.githubusercontent.com/assets/9618389/13585102/6bddc758-e47f-11e5-8f37-872fdb4b0cb8.png">

**Comment by jcabral02** [comment]
Yas e corrigió ese bug, saludos!
