### ISSUE TITLE
[QA] Teléfonos de contacto.

### ISSUE THREAD

**Issue by Vilhum** [onixmedia/Proeza#70]
Los teléfonos en contacto no aparecen en versión tablet y móvil
![12835041_10156581058175463_110856269_n](https://cloud.githubusercontent.com/assets/16924458/13588122/e78e2bd2-e492-11e5-87c5-e4d05cc78216.jpg)

**Comment by femedrano** [comment]
![12788109_10154125576531019_2043092217_n](https://cloud.githubusercontent.com/assets/16901017/13606673/7c2b7c98-e512-11e5-8c13-850b26a5bf79.jpg)
