### ISSUE TITLE
[QA] Ajustes de línea del tiempo

### ISSUE THREAD

**Issue by Vilhum** [onixmedia/Proeza#71]
Alinear texto y fechas con imagen
![12834540_10156581058255463_1925656304_n](https://cloud.githubusercontent.com/assets/16924458/13588176/63fd399c-e493-11e5-878a-df6c841d0668.jpg)

**Comment by femedrano** [comment]
![screen shot 2016-03-09 at 5 39 58 pm](https://cloud.githubusercontent.com/assets/16901017/13654450/02e798c8-e61e-11e5-80d9-37b5bd12e8cc.png)

Link: http://proeza.com.mx.c25.sitepreviewer.com/historia/

**Comment by mgl23** [comment]
Gracias :D
