### ISSUE TITLE
Secciónes: 5

### ISSUE THREAD

**Issue by mgl23** [onixmedia/Proeza#9]

**Comment by mgl23** [comment]
Crear template de sección para replicarlo.

**Comment by femedrano** [comment]
Link:
http://proeza.com.mx.c25.sitepreviewer.com/wp-demo/metalsa/

**Comment by mgl23** [comment]
Hay que corregir el bloque de bolsa de trabajo en el tamaño ''tablet'' no se adapta la imagen como en el home si se adapta. 
<img width="888" alt="captura de pantalla 2016-02-09 a la s 17 33 18" src="https://cloud.githubusercontent.com/assets/9618389/12934331/69e5a574-cf53-11e5-8260-54f39ec0cda3.png">

**Comment by femedrano** [comment]
![screen shot 2016-02-09 at 5 41 04 pm](https://cloud.githubusercontent.com/assets/16901017/12934460/54b59f96-cf54-11e5-9cab-b9fd86983348.png)
